"""
Strategy Optimizer (The Filter Layer)
Goal: Find the "Winning Zone" filters (Odds, Margin, Box) that turn the Pace Model profitable.
Input: safe_predictions.csv (Generated by backtest_safe_portfolio.py)
"""
import pandas as pd
import numpy as np

def optimize():
    print("Loading Predictions...")
    try:
        df = pd.read_csv('safe_predictions.csv')
    except FileNotFoundError:
        print("Error: safe_predictions.csv not found. Run backtest_safe_portfolio.py first.")
        return

    print(f"Loaded {len(df)} predictions.")
    
    # Pre-calc columns helpful for filtering
    # Start with simple "Predicted Winner" logic (Rank 1)
    df['RaceKey'] = df['MeetingDate'].astype(str) + df['TrackName'] + df['RaceID'].astype(str)
    
    # Calculate MARGIN (Lead over 2nd place prediction)
    # We need to know: Is this a "Strong" prediction (Lead > 0.2s) or "Weak" (Lead < 0.01s)?
    # For Split
    df['SplitMargin'] = df.groupby('RaceKey')['PredSplit'].transform(lambda x: x.nsmallest(2).iloc[1] - x.min())
    # Identify who IS the Rank 1
    df['IsPredSplitWin'] = (df['PredSplit'] == df.groupby('RaceKey')['PredSplit'].transform('min'))
    
    # For Overall (Pace)
    df['OverallMargin'] = df.groupby('RaceKey')['PredOverall'].transform(lambda x: x.nsmallest(2).iloc[1] - x.min())
    df['IsPredOverallWin'] = (df['PredOverall'] == df.groupby('RaceKey')['PredOverall'].transform('min'))
    
    # Define Filter Grids
    odds_min_grid = [1.5, 2.0, 3.0, 4.0]
    odds_max_grid = [5.0, 8.0, 10.0, 15.0, 30.0]
    margin_grid = [0.0, 0.05, 0.1, 0.2] # Seconds buffer
    
    strategies = [
        ('Rabbit', 'IsPredSplitWin', 'SplitMargin'),
        ('Dominator', 'IsPredOverallWin', 'OverallMargin'),
    ]
    
    results = []
    
    print("\nRunning Grid Search...")
    print(f"{'Strategy':<12} {'OddsRange':<10} {'Margin>':<8} {'Box':<5} | {'Bets':<6} {'Strike':<6} {'Profit':<8} {'ROI':<6}")
    print("-" * 80)
    
    for strat_name, flag_col, margin_col in strategies:
        # Base Subset (Rank 1s)
        base_df = df[df[flag_col] == True].copy()
        
        for o_min in odds_min_grid:
            for o_max in odds_max_grid:
                if o_min >= o_max: continue
                
                for marg in margin_grid:
                    # Filter
                    subset = base_df[
                        (base_df['Odds'] >= o_min) & 
                        (base_df['Odds'] <= o_max) &
                        (base_df[margin_col] >= marg)
                    ]
                    
                    if len(subset) < 100: continue
                    
                    wins = subset['IsWin'].sum()
                    n_bets = len(subset)
                    profit = (subset[subset['IsWin']==1]['Odds'] - 1).sum() - (n_bets - wins)
                    roi = profit / n_bets * 100
                    
                    if roi > 0: # Only show profitable configs
                        print(f"{strat_name:<12} {o_min}-{o_max:<4} {marg:<8.2f} {'All':<5} | {n_bets:<6} {wins/n_bets*100:<6.1f} {profit:<8.1f} {roi:<6.1f}")
                        
                        results.append({
                            'Strategy': strat_name,
                            'OddsMin': o_min,
                            'OddsMax': o_max,
                            'Margin': marg,
                            'Box': 'All',
                            'Bets': n_bets,
                            'Profit': profit,
                            'ROI': roi
                        })
                        
    # Test specific Box Filters for the best generic strategies
    # (Simplified to avoid combinatorial explosion)
    
    if not results:
        print("No generic strategies found. Trying Box specifics...")
    
    # Top 5 best generic results
    top_results = sorted(results, key=lambda x: x['Profit'], reverse=True)[:5]
    
    if top_results:
        print("\nDrilling down into Boxes for Top Strategies...")
        for r in top_results:
            strat_name = r['Strategy']
            o_min, o_max = r['OddsMin'], r['OddsMax']
            marg = r['Margin']
            flag_col = 'IsPredSplitWin' if strat_name == 'Rabbit' else 'IsPredOverallWin'
            margin_col = 'SplitMargin' if strat_name == 'Rabbit' else 'OverallMargin'
            
            base_df = df[
                (df[flag_col] == True) &
                (df['Odds'] >= o_min) & 
                (df['Odds'] <= o_max) & 
                (df[margin_col] >= marg)
            ]
            
            # Check each Box
            for box in [1, 2, 3, 4, 5, 6, 7, 8]:
                subset = base_df[base_df['Box'] == box]
                if len(subset) < 30: continue
                
                wins = subset['IsWin'].sum()
                n_bets = len(subset)
                profit = (subset[subset['IsWin']==1]['Odds'] - 1).sum() - (n_bets - wins)
                roi = profit / n_bets * 100
                
                if roi > 10: # Super niche
                    print(f"[NICHE] {strat_name} ${o_min}-{o_max} Mg>{marg} Box{box} | Bets:{n_bets} ROI:{roi:.1f}% Profit:${profit:.1f}")

if __name__ == "__main__":
    optimize()
